### ISSUE TITLE
searching for a dataset

### ISSUE THREAD

**Issue by Marensina** [Sirine-Kraiem/capstone-project#1]

**Comment by Sirine-Kraiem** [comment]
https://www.kaggle.com/datasets/kazireyazulhasan/19000-skincare-products-database-of-skinsort
https://www.kaggle.com/datasets/nadyinky/sephora-products-and-skincare-reviews?select=product_info.csv
https://www.kaggle.com/datasets/thedevastator/skincare-products-that-perform-the-best-at-sepho?select=brands_w_m_products.csv
